DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
     url(r'^links$', app.views.links, name='links'),
     url(r'^anketa$', app.views.anketa, name='anketa'),
     url(r'^newpost$', app.views.newpost, name='newpost'),
     url(r'^registration$', app.views.registration, name='registration'),
     url(r'^catalog$', app.views.catalog, name='catalog'),
     url(r'^trash$', app.views.trash, name='trash'),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
     url(r'^addtotrash/(?P<aid>\d+)/$', app.views.addtotrash, name='addtotrash'),
     url(r'^delproduct/(?P<did>\d+)/$', app.views.delproduct, name='delproduct'),
     url(r'^buyproduct/(?P<bid>\d+)/$', app.views.buyproduct, name='buyproduct'),
     url(r'^videopost$', app.views.videopost, name='videopost'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text


class AnketaForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
    tel = forms.CharField(label='Номер телефона', min_length=2, max_length=12)                          
    gender = forms.ChoiceField(label='Ваш пол',
                               choices=[('1','Мужской'), ('2','Женский')],
                               widget=forms.RadioSelect, initial=1)
    notice = forms.BooleanField(label='Получать новости сайта на e-mail?',
                                required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length=7)
    message = forms.CharField(label='Оставьте свой отзыв:',
                              widget=forms.Textarea(attrs={'rows':10, 'cols':40}))

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog #используемая модель
        fields = ('title', 'description', 'content', 'posted', 'author', 'image',)
        labels = {'title':"Заголовок",'description':"Краткое описание", 'content':"Содержание", 'posted':"Дата", 'author':"Автор", 'image':"Изображение",}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
<strong> Учим готовить торты, технологические карты приготовления с пошаговыми фотографиями📝
Справится любой, даже новичок. </strong>
<p></p>
{% endblock %}

app/templates/app/anketa.html
{% extends "app/layout.html" %}

{% block content %}

{% if form != None %}
 <br><h2>Отправьте, пожалуйста, заполненную анкету</h2><br>
<div>
    <form method="post">
      {% csrf_token %}
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
      {{ form.name }}<br>
      <label for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
      {{ form.city }}<br>
     <label for="{{ form.tel.id_for_label }}">{{ form.tel.label }}</label>
      {{ form.tel }}<br>
     <label for="{{ form.gender.id_for_label }}">{{form.gender.label }}</label>
      {{ form.gender }}
      <label for="{{ form.notice.id_for_label }}">{{form.notice.label }}</label>
      {{ form.notice }}<br><br>
      <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
      {{ form.email }}<br><br>
      <label for="{{ form.message.id_for_label }}">{{ form.message.label }}</label>
      {{ form.message }}<br><br>
    
       <button id="b1" type="submit">
           Отправить
       </button>
      </form>
  </div>
{% else %}
 <br><h2>Благодарим за предоставленную информацию!</h2>
 <h3>Вы сообщили о себе следующее:</h3>
 <u1>
     <li><span>Имя:</span> {{ data.name }}</li>
     <li><span>Город:</span> {{ data.city }}</li>
     <li><span>Номер телефона:</span> {{ data.tel }}</li>
     <li><span>Пол:</span>{{ data.gender }}</li>
     <li><span>Получать новости сайта на e-mail:</span> {{ data.notice }}</li>
     <li><span>E-mail:</span> {{ data.email }}</li>
     <li><span>Отзыв:</span> {{ data.message }}</li>
 </u1>
{% endif %}

<script>
   function b1_point() { $('#b1').css('color', 'yellow'); }
   function b1_unpoint() { $('#b1').css('color', 'red'); }
   function name_focus() { $('#id_name').css('background-color', 'Mediumaquamarine'); }
   function name_blur() { $('#id_name').css('background-color', 'white'); }
   function city_focus() { $('#id_city').css('background-color', 'Mediumaquamarine'); }
   function city_blur() { $('#id_city').css('background-color', 'white'); }
   function tel_focus() { $('#id_tel').css('background-color', 'Mediumaquamarine'); }
   function tel_blur() { $('#id_tel').css('background-color', 'white'); }
   function email_focus() { $('#id_email').css('background-color', 'Mediumaquamarine'); }
   function email_blur() { $('#id_email').css('background-color', 'white'); }
   function message_focus() { $('#id_message').css('background-color', 'Mediumaquamarine'); }
   function message_blur() { $('#id_message').css('background-color', 'white'); }

   $('#b1').mouseover(b1_point);
   $('#b1').mouseout(b1_unpoint);
   $('#id_name').focus(name_focus);
   $('#id_name').blur(name_blur);
   $('#id_city').focus(city_focus);
   $('#id_city').blur(city_blur);
   $('#id_tel').focus(tel_focus);
   $('#id_tel').blur(tel_blur);
   $('#id_email').focus(email_focus);
   $('#id_email').blur(email_blur);
   $('#id_message').focus(message_focus);
   $('#id_message').blur(message_blur);

</script>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{ title }}</h2> <br />

{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
    <img src="{{ post_1.image.url }}" alt=«Картинка статьи блога" width="350" height="300"/>
{% endif %}
<p> {{post_1.content|linebreaksbr}} </p> {# вывод текста по абзацам#}

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}
    <div>
         {{form.as_p}}
         <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>
{% else %}
    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}

{% for comment in comments %}
    <hr/>
    <h7> {{comment.date}} </h7>
    <h5> {{comment.author}} </h5>
    <p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

<p><a href="{% url 'blog' %}"> Назад </a></p>
{% endblock %}

app/templates/app/catalog.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Каталог товаров:</h2> <br />
<div class="row">
{% for post in posts %}
    <div class="col-md-4">
        <img src="{{ post.image.url }}" alt="Картинка" width="350" height="300"/>
        <h2> {{post.title}} </h2>
        <h3> {{post.description}} </h3>
        <h3> {{post.price}} </h3>
        <a href="{% url 'addtotrash' aid=post.id %}" class="btn btn-default">Купить</a>
    </div>
{% endfor %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Сам себе кондитер</h1>
    <p class="lead"> Здесь есть рецепты и лайфхаки, мастер-классы и, конечно, пошаговые инструкции с фото.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Лайфхаки</h2>
        <p>
           
        </p>
        <p><a class="btn btn-default" href="{% url 'videopost' %}">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Эксклюзивные рецепты</h2>
        <p>Рецепты собственной разработки, технологические карты приготовления тортов с фотографиями</p>
        <p><a class="btn btn-default" href="{% url 'catalog' %}">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Сделать заказ торта к вашему торжеству.</h2>
        <p>Оставьте свою зявку в разделе обратная связь и мы свяжемся с вами по электронной почте. </p>
        <p><a class="btn btn-default" href="{% url 'anketa' %}">Оставить заявку &raquo;</a></p>
    </div>
</div>
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000";>
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/banner1.jpg'%} " alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Здесь можно ознакомиться с информацией о нас.
                    <a class="btn btn-default" href="{% url 'about' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/banner2.jpg'%}" alt="Второй слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Блог с рецептами сладкой и сытной выпечкой.
                    <a class="btn btn-default" href="{% url 'blog' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banner4.jpg'%} " alt="Третий слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Обратная свзять.
                    <a class="btn btn-default" href="{% url 'anketa' %}">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Сам себе кондитер</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/logo.jpg' %}" alt="logo" width="60" height="60"/> </a> {#Логотип сайта#}
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'catalog' %}">Каталог</a></li>                  
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'anketa' %}">Обратная связь</a></li>
                    <li><a href="{% url 'trash' %}">Корзина</a></li> 
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - "Сам себе кондитер"</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
<!DOCTYPE html>
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block content %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <h2>{{ title }}</h2>
    <li /><a href="https://www.hlebpskov.ru/" target="_blank"> <img src="{% static 'app/content/pskhleb.png' %}" alt="Logo ph" /></a></ul><br />
    <li /><a href="https://craftology.ru/" target="_blank"> <img src="{% static 'app/content/craftology.png' %}" alt="Logo cl" /></a></ul><br />
    <li /><a href="https://homebaked.ru/" target="_blank"> <img src="{% static 'app/content/homebaked.png' %}" alt="Logo hb" /></a></ul><br />
</head>
<body>

</body>
</html>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальную учетную запись для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">{{ user.username }}</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}
    <h3>Добавить статью</h3>
    <form method="POST" enctype="multipart/form-data"  >  {% csrf_token %} 
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default" > Сохранить статью </button>
    </div>
    </form>
{% endblock %}

app/templates/app/registration.html
<{% extends "app/layout.html" %}
  {% block content %}
<h2>Регистрация пользователя</h2>
<form method="POST" > {% csrf_token %}
<div>
 {{ regform.as_p}}
 <button type="submit" class="save btn btn-default" > Зарегистрировать </button>
</div>
</form>
{% endblock %}

app/templates/app/trash.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Корзина:</h2> <br />
<div class="row">
{% for post in posts %}
    <div class="col-md-4">
        {% for post_1 in posts_1 %}
            {% if post.post_id == post_1.id %}
                <h2>Название: {{post_1.title}} </h2>
                <h3>Цена: {{post_1.price}} </h3>
            {% endif %}
        {% endfor %}
        <h3>Дата добавления: {{post.date}} </h3>
        <h3>Статус: {% if post.ready %} оплачен {% else %} не оплачен {% endif %}</h3>
        <a href="{% url 'buyproduct' bid=post.id %}" class="btn btn-default">Оплатить</a>
        <a href="{% url 'delproduct' did=post.id %}" class="btn btn-default">Удалить</a>
    </div>
{% endfor %}
</div>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}
   
<div>
      <h1>Лайфхак как присыпать края торта.</h1>  
        <VIDEO src="/media/media1.mp4" controls="controls" width="400" height="300" poster="/media/m1.png"></VIDEO>
    </div>
<hr/>
<div>
      <h1>Cakes.</h1>  
        <VIDEO src="/media/media2.mp4" controls="controls" width="400" height="300" poster="/media/m2.png"></VIDEO>
    </div>
    
{% endblock %}